### ISSUE TITLE
Style Improvements

### ISSUE THREAD

**Issue by pavanagrawal123** [pavanagrawal123/VSNotebooks#15]
Currently, I think there is a lot of wasted space for all the cards so I was planning on making the following changes:

- [X]  Reduce gap between cards
- [X]  Reduce border on cards to 1px and increase opacity to .4
- [x] Put the title and action buttons all in one line to save space.
- [x] Reduce excess space between the card bottom and next card. 
- [x] Fix expand button
- [x] Card controls should be visible 100% of the time.
Let me know if you want to see any other style changes in this issue!

**Comment by schrodog** [comment]
I agree with you. I think you can limit the gaps between cards as much as possible, reduce size of the 'expand' icon

**Comment by pavanagrawal123** [comment]
Great to hear!
Here's how it looks so far, I will be adding improvement with the expansion, I'm thinking of completely getting rid of it and replacing it with a 1-line preview of the output and then click to expand.
![image](https://user-images.githubusercontent.com/17802917/47599337-98081b00-d971-11e8-912a-814bcf824a34.png)

**Comment by schrodog** [comment]
i think there's still some space to reduce between output result and the triangle icon

**Comment by pavanagrawal123** [comment]
Yep, ideally I want to just get rid of it and do something like this.
![image](https://user-images.githubusercontent.com/17802917/47599427-cab31300-d973-11e8-9106-084d43064e80.png)
Of course it will look way better, this was just a quick mockup. If we did this, it would save a lot of space with the triangle, and would leave much more space for code/output.

**Comment by pavanagrawal123** [comment]
I ended up reducing the gap and the sizes of all the buttons and IMO it looks pretty nice this way.
![image](https://user-images.githubusercontent.com/17802917/47610813-44a2d500-da24-11e8-8547-3252a2b60950.png)
Do you think there should be any other changes in V1.5?

**Comment by pavanagrawal123** [comment]
Fixed and shipped.
