### ISSUE TITLE
Error could not start: Jupyter could not be executed automatically

### ISSUE THREAD

**Issue by faaip** [pavanagrawal123/VSNotebooks#21]
Hey Pavan!

Very excited for this tool and your fork. I'm running on macos, but cannot seem to get it to run. I'm also running the Python extension, where I have chosen a python3.7 interpreter installed using brew. I have also installed jupyter for this.

When trying to open output pane, I get an output pane stating that "Error could not start: Jupyter could not be executed automatically". Do you have any idea on how this could be resolved?

Thanks!

**Comment by pavanagrawal123** [comment]
Woohoo! I'm glad to hear the excitement!

Are you running on the beta version or the normal "VSNotebooks" extension?

Custom environments are only available in the beta version for now :)

**Comment by pavanagrawal123** [comment]
Due to inactivity, I'm closing this issue. If you have any questions in regards to this issue, please comment on this issue once again, and I'll open it again!

**Comment by MikeYuanMY** [comment]
Hi This is related to the issue on the main github https://github.com/neuron-team/vscode-ipe/issues/180#issuecomment-489601111

I have install this fork and still cannot open the out panel 
After I initiate the output panel, I can see the log stating the package is trying to "Starting a Jupiter Kernel at location /anaconda3/bin"

and it will say "Erro could not start: Jupyter could not be executed automatically"

I am on MacOs, Version 1.33.1 (1.33.1) and latest version of this fork

I am quite new to vs code, if you need more information, please tell me how i can get the system log for you. Thanks for looking into it.
