### ISSUE TITLE
[Long term feature request] Extend support to Javascript (extension)

### ISSUE THREAD

**Issue by schrodog** [pavanagrawal123/VSNotebooks#25]
This is a very long term development suggestion only, can be ignored for now.

Actually I think many dynamic languages can work with jupyter-notbook like developemnt environment. I think the most worthy language support candidate would be JS, given the massive community base and popularity. I not yet seen any usable notebook like environment for JS.

**Comment by fradav** [comment]
what about [this](https://github.com/n-riesco/ijavascript) ?

**Comment by schrodog** [comment]
> what about [this](https://github.com/n-riesco/ijavascript) ?

This one is very close to what I want, but sadly not available as extension in vscode. I think maybe we can use it as base and incorporate other new features discussed. :)
